### ISSUE TITLE
Pinger, nmdc: hubs operator: invalid syntax

### ISSUE THREAD

**Issue by Kcchouette** [direct-connect/go-dcpp#72] opened 2019-03-14 18:44 UTC
```
./dcping ping "dchub://stealthhub.ru:411"
2019/03/14 18:40:51 invalid info hubs operator: invalid syntax
{"name":"Stealth Group - Hub�","desc":"���������, �������� �������� � ���������� �������������! ������!!! ������� , �����!!! .px.","addr":["dchub://stealthhub.ru:411","dchub://localhost:411"],"soft":{"name":"PtokaX","ext":["NoHello","UserCommand","UserIP2","BotINFO","HubINFO"]},"users":631,"share":296853496399655,"status":"error"}
```

**Comment by dennwc** [comment] 2019-03-15 02:06
Cannot reproduce, probably happens because of specific user tag. Need to catch it with `--debug`.

**Comment by Kcchouette** [comment] 2019-05-03 19:19
I have another code now:
```
 ./dcping ping "dchub://stealthhub.ru:411" --encoding CP1251
2019/05/03 19:13:41 invalid hubs counts: "8/"
{"name":"Stealth Group - Hub™ - Ноу спам, ноу фэйк, ноу детское порно. Только приятное общение!","addr":["dchub://stealthhub.ru:411"],"soft":{"name":"PtokaX","ext":["ZPipe0","NoHello","UserCommand","UserIP2","BotINFO","HubINFO"]},"users":2044,"share":1292959386220070,"status":"error"}
```

And just after, I has work as nothing append:
```
 ./dcping ping "dchub://stealthhub.ru:411" --encoding CP1251
{"name":"Stealth Group - Hub™","desc":"Викторина, приятный колектив и адекватная администрация! Заходи!!! Общайся , Качай!!! .px.","addr":["dchub://stealthhub.ru:411","dchub://localhost:411"],"soft":{"name":"PtokaX","ext":["ZPipe0","NoHello","UserCommand","UserIP2","BotINFO","HubINFO"]},"users":2163,"share":1358776020911394}
```

**Comment by HadesDCH** [comment] 2019-11-23 04:45
Jus about how do i execute ping?
Whats the command line - where are the settings - how does it get hub addresses to ping etc...
Is there any documentation on this?
Can it ping hubs in strict TLS v.1.3?

Thanx for anyhelp.

**Comment by Kcchouette** [comment] 2019-11-23 10:36
@HadesDCH as it sems another issue (a doc one), in a perfect world, you would open a new issue

About you're asking, you execute ping using the dcping project on this repo ( https://github.com/direct-connect/go-dcpp/tree/master/cmd/dcping )
You can see some option here: https://github.com/direct-connect/go-dcpp/blob/ac062d9d58da15ecda0c971f455c2a80f1b6c76e/cmd/dcping/main.go#L120-L131

> how does it get hub addresses to ping

from yourself

For tls v1.3, test it and report the problem in another issue if problem occur

**Comment by HadesDCH** [comment] 2019-11-23 17:32
Yes - i'm sorry, i should've opened n new issue.
Thanx for your help. Now i know.
I will def test it tonight and if something comes up this time i will open an issue ticket.

**Comment by dennwc** [comment] 2020-02-09 16:42
Seems like using `--encoding CP1251` works, so I'm closing this one. Feel free to reopen.

**Closed by dennwc** 2020-02-09 16:42 UTC
